config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users

  get 'products/index'
  post 'order_items/add'

  get 'orders/index'
  post 'orders/complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!

  def add
    product_id = params.permit(:product_id)[:product_id]
    product = Product.find(product_id)
    order = current_user.orders.last
    if order.nil? || order.completed
      order = current_user.orders.new
    end
    item = order.order_items.where(product: product).first
    if item.nil?
      item = order.order_items.new
      item.product = product
      item.quantity = 1
    else
      item.quantity = item.quantity + 1
    end
    item.save
    redirect_to products_index_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @current = current_user.orders.where(completed: false).last
    @completed_orders = current_user.orders.where(completed: true)
  end

  def complete
    id = params.permit(:order_id)[:order_id]
    order = current_user.orders.find(id)
    if !order.completed 
      order.completed = true
      order.save
    end
    redirect_to orders_index_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab2</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
      <p>Logged as: <%= current_user.email %></p>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
      <%= link_to('Login', new_user_session_path)  %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/orders/_order.html.erb
<div class="order">
    <p>
        <%= order.created_at %>
    </p>
    <ul>
        <% order.order_items.each do |item| %>
            <li>
                <%= item.product.name %> - <%= item.quantity %>
            </li>
        <% end %>
    </ul>
    <% if !order.completed %>
        <%= form_with url: orders_complete_path do |form|%>
            <%= form.hidden_field :order_id, :value => order.id %>
            <%= form.submit "Complete" %>
        <% end %>
    <% end %>
</div>

app/views/orders/index.html.erb
<h2>Order list</h2>
<% if !@current.nil? %>
    <h3>Current order</h3>
    <%= render @current %>
<% end %>
<h3>Completed orders</h3>
<%= render @completed_orders %>

<%= link_to 'Products', products_index_path %>

app/views/products/_product.html.erb
<div class="product">
    <%= product.name %> - <%= product.price %> gold
    <% if user_signed_in? %>
        |
        <%= form_with url: order_items_add_path, class: 'add-form' do |form|%>
            <%= form.hidden_field :product_id, :value => product.id %>
            <%= form.submit "Add" %>
        <% end %>
    <% end %>
</div>

app/views/products/index.html.erb
<h2>Product list</h2>
<%= render @products %>

<%= link_to 'Orders', orders_index_path %>